"""empty message

Revision ID: 75e5d878c272
Revises: 
Create Date: 2020-07-18 08:48:49.169908

"""
from alembic import op
import sqlalchemy as sa
from werkzeug.security import generate_password_hash


# revision identifiers, used by Alembic.
revision = '75e5d878c272'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###

    op.execute('INSERT INTO "roles" ("name") VALUES (\'admin\')')
    op.execute('INSERT INTO "roles" ("name") VALUES (\'investor\')')

    pwdhash = generate_password_hash('Greed1sG000d')
    op.execute(
        'INSERT INTO "users" ("id", "password", "email") VALUES(\'gordon-root\',\'' + pwdhash + '\',\'ggekko@gekkoco.com\')')
    op.execute('INSERT INTO "user_roles" ("user_id", "role_id") VALUES(\'gordon-root\',1)')



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
